// Dodać pole z linkiem do trailera

export const moviesDatabase = [
    {
        lp: 1,
        title: "Fast and Furious",
        category: 'action',
        year: '2017',
        rating: 5,
        director: 'F. Gary Gary',
        mainActors: ['Vin Diesel', 'Dwayne Johnson', 'Charlize Theron', 'Jason Stathman', 'Ludacris', 'Scott Eastwood', 'Nathalie Emmanuel', 'Paul Walker'],
        shortDescription: 'Dominic and Letty are on their honeymoon in Cuba when Cipher suddenly appears. The woman turns out to be a cyberterrorist who engages Toretto in working for her. The future of the "fast family" is put to the test, so Deckard Shaw is involved in helping Torettas friends.',
        longDescription: 'Dominic Torreto (Vin Diesel) and his newly married wife Letty (Michelle Rodriguez) enjoy each other on their honeymoon. After Brian and Mia decided to quit their job, the rest of the group also decided to live a normal life. The apparent calm, however, is broken when a mysterious woman named Cipher (Charlize Theron) seduces Dominic and drag him back into the dangerous world of crime. The man friends decide not to let this happen. The group decides to do whatever it takes to stop the dangerous anarchist and save the man who made them a family.',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2017',
            month: '4'
        },
        age: 12,

    },
    {
        lp: 2,
        title: "Mortal Engines",
        category: 'sci-fi',
        year: '2018',
        rating: 3,
        director: "",
        mainActors: ['Robert Sheean', 'Hera Hilmar', 'Hugo Weaving'],
        shortDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo dictum malesuada. Morbi et massa et nisi faucibus tincidunt nec vel dolor. Morbi malesuada felis a nibh placerat condimentum. Duis euismod ultrices semper.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2018',
            month: '11'
        },
        age: 12,
    },
    {
        lp: 3,
        title: "Love and Monsters",
        category: 'action',
        year: '2018',
        rating: 4,
        director: "",
        mainActors: ['Jessica Henwick', 'Dylan O’Brien', 'Ariana Greenblatt', 'Michael Rooker'],
        shortDescription: 'A young man learns how to survive the monsters apocalypse with the help of an experienced hunter.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: './images/MortalEngines/img1.jpg',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2010',
            month: '10'
        },
        age: 12,
    },
    {
        lp: 4,
        title: "The devil all the time",
        category: 'drama',
        year: '2020',
        rating: 4,
        director: "",
        mainActors: ['Tom Holland', 'Sebastian Stan', 'Robert Pattinson'],
        shortDescription: 'The post-war reality is full of corruption and brutality. People steeped in evil surround a young man who protects his loved ones with dedication.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2020',
            month: '9'
        },
        age: 16,
    },
    {
        lp: 5,
        title: "Five feet apart",
        category: 'drama',
        year: '2018',
        rating: 4,
        director: "",
        mainActors: ['Cole Sprouse', 'Haley Lu Richardson', 'Moisés Arias', 'Claire Forlani'],
        shortDescription: 'Stella Grants life changes when she meets patient Will Newman while in hospital.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2019',
            month: '3'
        },
        age: 8,
    },
    {
        lp: 6,
        title: "Ritual",
        category: 'horror',
        year: '2018',
        rating: 3,
        director: "David Bruckner",
        mainActors: ['Rafe Spall', 'Rob James‑C', 'Arsher Ali', 'Sam Troughton'],
        shortDescription: 'The young deacon is unsure of his calling. He goes to the Vatican, where, under the watchful eye of an eccentric clergyman, he learns about the dark side of the Catholic Church.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2017',
            month: '9'
        },
        age: 16,
    },
    {
        lp: 7,
        title: "All the bright places",
        category: 'romance',
        year: '2018',
        rating: 3,
        director: "Brett Haley",
        mainActors: ['Elle Fanning', 'Justice Smith', 'Felix Mallard', 'Alexandra Shipp'],
        shortDescription: 'A teenage Violet standing on the edge of the bridge notices Theodore running by. The boy does everything to persuade her to participate in the school project.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2020',
            month: '2'
        },
        age: 12,
    },
    {
        lp: 8,
        title: "Passengers",
        category: 'sci-fi',
        year: '2018',
        rating: 4,
        director: "Morten Tyldum",
        mainActors: ['Jennifer Lawrence', 'Chris Pratt'],
        shortDescription: 'One of the passengers of the interstellar liner is awakened several decades ahead of schedule. Aware of his position, he decides to take a step that will have irreversible consequences.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2016',
            month: '12'
        },
        age: 12,
    },
    {
        lp: 9,
        title: "Bumblebee",
        category: 'family',
        year: '2018',
        rating: 3,
        director: "Travis Knight",
        mainActors: ['John Cena', 'actPamela Adlon'],
        shortDescription: 'The Autobot Bumblebee escaping from Cybertron reaches Earth, where he meets teenage Charlie.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2019',
            month: '1'
        },
        age: 8,
    },
    {
        lp: 10,
        title: "Bird box",
        category: 'thriller',
        year: '2018',
        rating: 5,
        director: "Susanne Bier",
        mainActors: ['actor1', 'actor2'],
        shortDescription: 'A story about a world that has been taken over by creatures that cannot be looked at without dying.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2018',
            month: '12'
        },
        age: 16,
    },
    {
        lp: 11,
        title: "Desperado",
        category: 'action',
        year: '2018',
        rating: 5,
        director: "Robert Rodriguez",
        mainActors: ['Antonio Banderas', 'Salma Hyek'],
        shortDescription: 'El Mariachi, a former musician with a case full of weapons, shows up in a small town. He is looking for his beloveds killer to avenge her death.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: './images/FastAndFurious8/img1.jpg',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '1995',
            month: '4'
        },
        age: 12,
    },
    {
        lp: 12,
        title: "Godzilla 2: King of the monsters",
        category: 'sci-fi',
        year: '2018',
        rating: 5,
        director: "Michael Dougherty",
        mainActors: ['Millie Bobby Brown', 'Kyle Chandler'],
        shortDescription: 'With a new threat, the Monster King returns to restore balance to nature.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2010',
            month: '6'
        },
        age: 12,
    },
    {
        lp: 13,
        title: "Enola Holmes",
        category: 'family',
        year: '2018',
        rating: 3,
        director: "Harry Bradbeer",
        mainActors: ['Millie Bobby Brown', 'Louis Partridge', 'Henry Cavill'],
        shortDescription: 'On her sixteenth birthday, Enola Holmes discovers that her mother has disappeared. The teenager goes to the care of her older brothers: Sherlock and Mycroft.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2020',
            month: '9'
        },
        age: 8,
    },
    {
        lp: 14,
        title: "White tiger",
        category: 'drama',
        year: '2018',
        rating: 5,
        director: "Ramin Bahrani",
        mainActors: ['Priyanka Chopraor1', 'Adarsh Gourav'],
        shortDescription: 'An ambitious Indian driver uses his wits to break out of poverty and reach the top.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2021',
            month: '1'
        },
        age: 16,
    },
    {
        lp: 15,
        title: "The kissing booth 2",
        category: 'comedy',
        year: '2018',
        rating: 4,
        director: "Vince Marcello",
        mainActors: ['Taylor Zakhar Perez', 'Jacob Elordi', 'Joey King'],
        shortDescription: 'Teen Elles first kiss leads to a forbidden romance with a hunk in the school, which risks losing her best friend.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2020',
            month: '7'
        },
        age: 12,
    },
    {
        lp: 16,
        title: "The longest Ride",
        category: 'family',
        year: '2018',
        rating: 5,
        director: "Stephen Chbosky",
        mainActors: ['Jacob Tremblay', 'Julia Roberts', 'Owen Wilson'],
        shortDescription: 'Auggie was born with a deformed face. In the new school, the boy wants to prove to his peers that beauty is more than looks.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2002',
            month: '6'
        },
        age: 8,
    },
    {
        lp: 17,
        title: "Lion King",
        category: 'family',
        year: '2018',
        rating: 5,
        director: "Rob Minkoff",
        mainActors: [' Jeremy Irons', 'James Earl Jones'],
        shortDescription: 'As a result of Scars ruse, the rightful ruler of the African savannah, Simba, is banished. Together with two friends, he intends to regain the throne.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '1994',
            month: '11'
        },
        age: 4,
    },
    {
        lp: 18,
        title: "Lord of Rings: The two towers",
        category: 'fantasy',
        year: '2018',
        rating: 4,
        director: "Peter Jackson",
        mainActors: ['Viggo Mortensen', 'Orlando Bloom', 'Liv Tyler', 'Elijah Wood'],
        shortDescription: 'The Fellowship of the Ring is shattered, but desperate Frodo wants to fulfill his task at all costs. Aragorn and his companions prepare to repel the attack of Saruman hordes.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2003',
            month: '1'
        },
        age: 12,
    },
    {
        lp: 19,
        title: "Transformers: Last Knight",
        category: 'sci-fi',
        year: '2018',
        rating: 4,
        director: "Michael Bay",
        mainActors: ['Mark Wahlberg', 'Isabela Moner', 'Laura Haddock'],
        shortDescription: 'As the world of Transformers and humans is at war, Cade Yeager and his companions embark on a journey to avert destruction.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '2017',
            month: '6'
        },
        age: 12,
    },
    {
        lp: 20,
        title: "Cap II from Beverly Hills",
        category: 'comedy',
        year: '2018',
        rating: 4,
        director: "Martin Brest",
        mainActors: ['Eddie Murphy', 'Judge Reinhold', 'John Ashton'],
        shortDescription: 'Police officer Axel Foley begins an investigation on his own when his friend is killed.',
        longDescription: 'Nulla tincidunt pharetra facilisis. Sed luctus, dolor mollis maximus semper, augue lorem laoreet eros, sit amet blandit sem ante vitae justo. Suspendisse nec ultrices urna. Donec magna purus, efficitur vel aliquet vitae, auctor eget erat. Vivamus non accumsan orci. Sed tempus nisi non justo imperdiet, quis lacinia odio porttitor. Aliquam sit amet vestibulum est. Phasellus bibendum, mauris sed efficitur pharetra, libero ex volutpat velit, a pretium velit augue in arcu. Pellentesque vehicula pulvinar libero, feugiat porttitor quam pretium eu. Donec tempus vitae nunc nec ultricies. Curabitur lacinia elit ante, et varius urna commodo ultricies. Vestibulum nec hendrerit lectus. Maecenas fermentum sit amet leo vel dapibus. Ut vehicula ante nunc, nec lobortis quam vehicula sed. Praesent commodo imperdiet ipsum, id scelerisque diam egestas et. ',
        photoOfficial: '',
        additionalPhotos: ['zdjęcie dodatkowe'],
        premiere: {
            year: '1984',
            month: '12'
        },
        age: 12,
    },
]
